apiVersion: v2
name: tibber-exporter
version: 2.1.0
description: Tibber prometheus exporter
type: application
keywords:
  - tibber
  - prometheus
  - grafana
  - monitoring
home: https://github.com/terjesannum/tibber-exporter
maintainers:
  - name: Terje Sannum
    email: terje@offpiste.org
    url: https://github.com/terjesannum
annotations:
  artifacthub.io/images: |
    - name: tibber-exporter
      image: ghcr.io/terjesannum/tibber-exporter:latest
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
  artifacthub.io/screenshots: |
    - title: Grafana dashboard
      url: https://raw.githubusercontent.com/terjesannum/tibber-exporter/master/grafana/dashboard.png
    - title: Grafana dashboard without Pulse
      url: https://raw.githubusercontent.com/terjesannum/tibber-exporter/master/grafana/dashboard-without-pulse.png
